# logging settings
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      sia:
        sia: trace
# Server
server:
  error:
    include-message: always
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://database-spring-boot.cge0w206bro6.us-east-1.rds.amazonaws.com:3306/sia?useSSL=false
    username: admin
    password: hdrFKDSDNr1*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop


